//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDITORIUM
    {
        public string AUDITORIUM1 { get; set; }
        public string AUDITORIUM_TYPE { get; set; }
        public Nullable<int> AUDITORIUM_CAPACITY { get; set; }
        public string AUDITORIUM_NAME { get; set; }
    
        public virtual AUDITORIUM_TYPE AUDITORIUM_TYPE1 { get; set; }
    }
}
