//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public int IDSTUDENT { get; set; }
        public Nullable<int> IDGROUP { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> BDAY { get; set; }
        public byte[] STAMP { get; set; }
        public string INFO { get; set; }
        public byte[] FOTO { get; set; }
    
        public virtual GROUPS GROUPS { get; set; }
    }
}
