//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER
    {
        public string TEACHER1 { get; set; }
        public string TEACHER_NAME { get; set; }
        public string GENDER { get; set; }
        public string PULPIT { get; set; }
    
        public virtual PULPIT PULPIT1 { get; set; }
    }
}
